rcore-os/zCore

- zircon-object/src/vm/vmar.rs
There are  two kinds of possible deadlock bugs in vmar.rs:
1. Double-Lock
In `fn map_ext`:
https://github.com/rcore-os/zCore/blob/bf9166cb8be99496b4678ef438d65e22eeac8f28/zircon-object/src/vm/vmar.rs#L181-L193
https://github.com/rcore-os/zCore/blob/bf9166cb8be99496b4678ef438d65e22eeac8f28/zircon-object/src/vm/vmar.rs#L213-L217
The first lock `self.inner.lock()` is on Line 181.
Then `self.unmap()` is called on Line 193.
The second lock is on Line 217.
The fix is to add `fn unmap_inner`, a no-lock version of `fn unmap`, and pass `&mut VmarInner` into it. `self.inner.lock()` is required before calling it.
2. Locks in conflicting orders
`self.inner.lock()` is called before `self.page_table.lock()` on L780-786 and L687-688.
https://github.com/rcore-os/zCore/blob/bf9166cb8be99496b4678ef438d65e22 …
> zircon-object: fix possible deadlocks in vmar.rs

- .github/workflows/main.yml
This PR adds workflow scripts to automatically deploy documents to `gh-pages` branch from new commits on master.
> Deploy docs on GitHub Actions

- README.md
- zCore/src/main.rs
Parsing kernel command line from device tree 
to pass CI test
> Parsing kernel command line from device tree to CI test

- kernel-hal/src/bare/arch/x86_64/drivers.rs
- linux-object/Cargo.toml
- linux-object/src/fs/devfs/mod.rs
- linux-object/src/fs/devfs/uartdev.rs
- linux-object/src/fs/mod.rs
- linux-object/src/time.rs
- linux-syscall/Cargo.toml
- linux-syscall/src/file/file.rs
- linux-syscall/src/file/stat.rs
- loader/Cargo.toml
- zCore/Cargo.toml
- zCore/Makefile
- 修正 `TimeSpec` 定义
- 实现串口伪文件并挂载
> TimeSpec & uart device file

- Makefile
update submodule : tests, change status of some testcases.
> change the url of libc-test, in order to fix some compile error.

- drivers/src/io/mmio.rs
- drivers/src/io/mod.rs
- drivers/src/io/pmio.rs
- drivers/src/irq/riscv_plic.rs
- drivers/src/uart/mod.rs
- drivers/src/uart/uart_16550.rs
- kernel-hal/src/bare/arch/x86_64/cpu.rs
- kernel-hal/src/bare/arch/x86_64/drivers.rs
- kernel-hal/src/bare/arch/x86_64/special.rs
- zircon-object/src/dev/pci/bus.rs
- zircon-object/src/dev/pci/config.rs
- zircon-object/src/dev/pci/mod.rs
- zircon-object/src/dev/pci/pmio.rs
- zircon-syscall/src/pci.rs
- 根据 [wikipedia](https://en.wikipedia.org/wiki/Memory-mapped_I/O)，`pio` 改名 `pmio`
- 为 `Mmio` 读写增加内存屏障
- 为 io 补充文档
> refactor(drivers): 修改 device io

- .github/scripts/add-doc-index.sh
- .github/scripts/install-deps.sh
- .github/scripts/install-qemu.sh
- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/test.yml
1. 多处需要同步修改的字段定义成 env 变量，方便修改，不易错漏；
2. ci 脚本中部分重复的 shell 命令，封装成 bash 脚本，供 ci 调用，让主逻辑更清晰，修改时也方便找；
3. 部分格式修订
> refactor(github ci): 重构github ci脚本

- drivers/src/net/loopback.rs
- kernel-hal/src/common/user.rs
- linux-object/src/net/mod.rs
- linux-object/src/net/netlink.rs
- linux-object/src/net/socket_address.rs
- linux-syscall/src/lib.rs
- linux-syscall/src/net.rs
add NetLink socket, support ip addr command.
> add NetLink socket, support ip addr command.

- zCore/build.rs
- zCore/src/platform/x86/linker.ld
> miner update: add sbss sdata srodata in linker.ld

- linux-object/src/net/mod.rs
- linux-syscall/src/lib.rs
- linux-syscall/src/net.rs
1. 增加 getsockopt 系统调用的实现
2. 重构 syscall net 部分代码
3. 增加 syscall net 部分文档
> feat(syscall): add getsockopt

- linux-syscall/src/net.rs
> fix: format

- kernel-hal/Cargo.toml
- zCore/Cargo.toml
- zCore/src/platform/riscv/entry.rs
> refactor(zCore): update dtb-walker to 0.1.3

- linux-object/src/net/mod.rs
- linux-object/src/net/raw.rs
- linux-syscall/src/net.rs
> feat(socket): add raw socket

- .github/workflows/build.yml
- .github/workflows/docs.yml
- drivers/Cargo.toml
> fix(github action): 生成整个工作空间的文档

- drivers/src/uart/uart_allwinner.rs
> fix(d1): 在老式串口助手上换行

- .github/workflows/test.yml
- Cargo.lock
- README.md
- docs/README_EN.md
- drivers/Cargo.toml
- xtask/src/arch.rs
- xtask/src/commands.rs
- xtask/src/main.rs
- zCore/src/platform/riscv/boot_page_table.rs
> 更新文档，介绍 zCore 硬件支持情况

- Cargo.lock
- kernel-hal/src/common/vdso.rs
- zCore/src/platform/riscv/entry.rs
> fix(kernel-hal): vdso version string 可能超过 64 字节

- .github/workflows/build.yml
- Cargo.lock
> fix: 修复定时 CI 不过的问题

- xtask/CHANGELOG.md
- xtask/src/linux/test.rs
> fix: 删除 libc-test 不需要的文件

- Cargo.lock
- zCore/src/memory.rs
> fix(zCore): nezha 上启动需要更大的启动堆

- Cargo.lock
- drivers/src/builder/devicetree.rs
> 使用 feature 控制哪吒打开所有串口
